# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 18:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190418_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
